version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    container_name: cassandra
    networks:
      - app-tier
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CQL_PORT_NUMBER=9042
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

  fastapi:
    container_name: fastapi
    networks:
      - app-tier
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 8080:8000
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PWD=cassandra
    depends_on:
      - cassandra
    command: python3 -m app

  react:
    container_name: react
    networks:
      - app-tier
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    depends_on:
      - fastapi
